### ISSUE TITLE
Deserializer drops source for custom errors

### ISSUE THREAD

**Issue by wcarmon** [toml-rs/toml#374] opened 2022-11-24 17:30 UTC
The `toml::de::Deserializer` is dropping "real" custom errors (by converting them to string, and dropping all other properties)

The `Custom` variant lacks a "source" or some other indicator of the original error.
- See https://github.com/toml-rs/toml/blob/main/crates/toml/src/de.rs#L162

We're locked into using `toml::de::Error` because `toml::de::Deserializer` has `toml::de::Error` associated
- https://github.com/toml-rs/toml/blob/main/crates/toml/src/de.rs#L206

Here is an MWE which demonstrates the issue
```rust
use serde::Deserialize;

#[derive(Clone, Debug, Eq, thiserror::Error, PartialEq)]
enum CustomError {
    #[error("something bad happened")]
    SomethingBad(String),
}

#[derive(Clone, Debug, Deserialize)]
#[serde(try_from = "ForSerde")]
struct Quux {
    bar: String,
}

impl Quux {
    pub fn new(s: &str) -> Result<Self, CustomError> {
        let q = Quux { bar: s.to_owned() };
        q.validate()?;
        Ok(q)
    }

    fn validate(&self) -> Result<(), CustomError> {
        Err(CustomError::SomethingBad("boom".to_owned()))
    }
}

#[derive(Deserialize)]
struct ForSerde {
    pub baz: String,
}

impl TryFrom<ForSerde> for Quux {
    type Error = CustomError;

    fn try_from(v: ForSerde) -> Result<Self, Self::Error> {
        Quux::new(&v.baz)
    }
}

#[cfg(test)]
mod tests {
    use std::error::Error;

    use toml::Deserializer;

    use super::*;

    #[test]
    fn should_return_custom_error() {
        let toml_str = r#"baz = "zum""#;

        let res = toml::from_str::<Quux>(&toml_str);
        let err: toml::de::Error = res.unwrap_err();

        // *****
        // This is the problem
        // There is no way to retrieve the CustomError
        assert!(err.source().is_none());

        // So this also fails
        if let Some(CustomError::SomethingBad(_)) = err.source() {
            // ...
        }
    }
}
```

**Comment by epage** [comment] 2023-01-18 18:26
From what I understand, an error should not `Display` its `source()` but should let the caller decide how to iterate `source`s, `Display`ing them.

The problem is that users custom error is the message to `Display` in the error, so if someone walked `source`, then it would be `Display`ed twice.

Looking at what `serde_json` does,
- It does `Display` io errors as well as report them in `source` ([source](https://docs.rs/serde_json/latest/src/serde_json/error.rs.html#318))
- It does `to_string()` all user-provided errors ([source](https://docs.rs/serde_json/latest/src/serde_json/error.rs.html#362))
  - Looking at [serde:de::Error](https://docs.rs/serde/latest/serde/de/trait.Error.html), it appears this is a limitation with `serde` and we can't really do anything about it

Since this is a limitation of serde, I'm going to go ahead and close this as Not Planned

**Closed by epage** 2023-01-18 18:26 UTC
