### ISSUE TITLE
[Bug] `de::from_str` has overly strict generic restrictions.

### ISSUE THREAD

**Issue by Embers-of-the-Fire** [toml-rs/toml#739] opened 2024-06-01 06:36 UTC
## Summary

Currently, `toml::de::from_str` has a signature like this:

```rust
pub fn from_str<T>(s: &'_ str) -> Result<T, Error>
where
    T: serde::de::DeserializeOwned, // note this
{
    T::deserialize(Deserializer::new(s))
}
```

Based on both `serde`'s suggestion and the actual method implementation, this should not be `DeserializeOwned`. This issue has limited impact in practical use, but for some generic implementations may lead to more complex signatures and thus cascading contagion.

## Solution

Simply change the `DeserializeOwned` into `Deserialize<'de>`.

**Comment by epage** [comment] 2024-06-01 13:34
Closing as this is a duplicate of #490

**Closed** 2024-06-01 13:34 UTC
