### ISSUE TITLE
How can you place a comment on a key inside a table?

### ISSUE THREAD

**Issue by zkldi** [toml-rs/toml#581] opened 2023-07-12 12:14 UTC
I have some toml like:
```toml
[audio]
driver = "whatever"
buf_size = 512
```

I'd like to serialize this to:
```toml
[audio]
driver = "whatever"
# here's a comment about buf_size
# with some advice
buf_size = 512
```

You can attach keys onto values, but if you use `set_prefix`, you get invalid output like:
```toml
buffer =
# Controls how many samples are buffered into the audio card.
512
```

`set_suffix` produces valid toml, but in the wrong place.
```toml
buffer = 512
# Controls how many samples are buffered into the audio card.
```
Is there any way I can attach a comment that goes *above* the key, without adding a suffix to every preceding value (which might fall out of sync with my structs and all that jazz).

**Comment by epage** [comment] 2023-07-12 13:29
With [`Table::get_key_value_mut`](https://docs.rs/toml_edit/latest/toml_edit/struct.Table.html#method.get_key_value_mut) you can provide a prefix to a key.

One tip for this is if you parse your intended document with `toml_edit` you can see how it will store your data and then look up the APIs for reproducing that.

**Comment by zkldi** [comment] 2023-07-12 13:39
ah yeah this works. For anyone looking for this in the future, you can use something like:
```rs
        if let Some(tbl) = doc["audio"].as_table_mut() && let Some((mut key, _)) = tbl.get_key_value_mut("buffer") {
            key.decor_mut().set_prefix("# hello world!\n"));
        }
```
which will serialize into
```toml
[audio]

# hello world!
buffer = 512
```

*****
Are there any plans to make utility functions for this - perhaps making the API a bit easier to discover and use? As it stands this is a little unwieldy.

**Comment by epage** [comment] 2023-07-12 13:48
There are a lot of different use cases, so its hard to say what utilities would be useful enough generally to build directly in.

As the question has been answered, I'm going to go ahead and close this

**Closed by epage** 2023-07-12 13:48 UTC
